[tool.poetry]
name = "nonebot_plugin_ayaka_timezone"
version = "0.4.1"
description = "时区助手"
authors = ["Su <wxlxy316@163.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/bridgeL/nonebot-plugin-ayaka-timezone"
packages = [
    { include = "ayaka_timezone.py", from = "." },
]


[tool.poetry.dependencies]
ayaka = ">=0.0.2.0, <0.0.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
