[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qtbox"
version = "0.0.7"
authors = [
  { name="Louis Ren", email="louasure@126.com" },
]
description = "Find your target qt widget here."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
  "PyQt5",
  "pygments"
]

[project.scripts]
qtbox = "qtbox.window:main"

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"