[tool.poetry]
name = "ptt-clk-mal"
version = "0.1.1.5"
description = "A small timer help make your time used better,inspired by tomatoclock."
authors = ["MALossov <lshy1104@163.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "ptt_clk_mal"}]

[tool.poetry.dependencies]
python = "^3.7"
rich = "^13.0.0"
PyYAML = "^6.0"

[tool.poetry.scripts]
pttClk = 'ptt_clk_mal.pc_parser:cli'

[[tool.poetry.source]]
name = "tsinghua-pypi"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"