[project]
name = "gqf"
version = "2023.1.30-5"
authors = [
  { name="gqf", email="guanworkmail@163.com" },
]
description = "misc functions"
classifiers = [
    "Programming Language :: Python :: 3"
]