[tool.poetry]
name = "trabalho-individual-gces"
version = "0.1.1"
description = ""
authors = ["italofernandes13 <italoserra99@gmail.com>"]
readme = "README.md"
packages = [{include = "src/"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
