[tool.poetry]
name = "kTemplate"
version = "0.2.0"
description = "a minimalist python html template lib"
authors = ["Kelvin Ng <hoishing@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/hoishing/kTemplate"
homepage = "https://hoishing.github.io/kTemplate"
keywords = ["template", "html", "jinja"]
classifiers = [
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Intended Audience :: Developers",
  "Framework :: Flask",
  "Framework :: FastAPI",
  "Development Status :: 4 - Beta",
]


[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.0.4"
mkdocstrings = { extras = ["python"], version = "^0.19.1" }
genbadge = { extras = ["coverage"], version = "^1.1.0" }

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
coverage = "^7.0.4"
black = "^22.12.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.docs]
optional = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
