[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "apiogram"
version = "0.2.0"
authors = [
    { name = "Alexander Majorov", email = "alexander.majorov@gmail.com" },
]
description = "A simple library for easy work with key-value storages and document databases"
readme = "README.md"
requires-python = ">=3.10.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/frontdevops/apiogram"
"Documentation" = "https://github.com/frontdevops/apiogram/blob/main/README.md"
"Bug Tracker" = "https://github.com/frontdevops/apiogram/issues"
