[tool.poetry]
name = "leximpact-aggregates"
version = "0.0.20"
description = "Store aggregates of french data."
authors = ["LexImpact"]
license = "AGPL-3.0"
#packages = [
#    { include = "leximpact_aggregates" },
#    { include = "aggregates/**/*.yaml" },
#]


[tool.poetry.dependencies]
python = "^3.8"
nbdev = "^2.0.0"
leximpact-socio-fisca-simu-etat = "^0.1.4"
openpyxl = "^3.0.9"
pre-commit = "^2.17.0"
pydantic = "^1.9.0"
matplotlib = "^3.5.1"
dataclasses-json = "^0.5.7"
StrEnum = "^0.4.7"
ipykernel = "^6.15.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
nbqa = "^1.3.1"
papermill = "^2.3.4"
tqdm = "^4.64.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
