[tool.poetry]
name = "wejr"
version = "0.1.1"
description = "Communication via websocket in JSON-RPC way"
authors = ["Wasth <riasta@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
channels = "^4.0.0"
channels-redis = {version = "^4.0.0", optional = true}


[tool.poetry.extras]
redis = ["channels-redis"]


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
tox = "^4.3.5"
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
