[tool.poetry]
name = "moviesorter"
version = "0.0.9"
description = ""
authors = []
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.scripts]
moviesorter = "moviesorter.cli:main"

[tool.poetry.dependencies]
python = "^3.11"
PyYAML = "^6.0"
pydantic = "^1.10.4"
click = "^8.1.3"
aiohttp = "^3.8.3"
rich = "^13.1.0"
async-cache = "^1.1.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"
mock = "^5.0.1"

[tool.poetry-version-plugin]
source = "init"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
