[tool.poetry]
name = "EraCore"
version = "0.0.5"
description = "Core"
license = "MIT"
authors = ["Eragod <eragod1337@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
