[tool.poetry]
name = "topping"
version = "0.1.1"
description = "Topping is a Python library for tracking function data."
authors = ["jenz <2025.jenz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
rich = "^13.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
