[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "tif"
version = "1.0.0"
authors = [
  { name="Carlo Tasca", email="c.tasca.tif@gmail.com" },
]
description = "TIF Python Package"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ctasca/tif"
"Bug Tracker" = "https://github.com/ctasca/tif/issues"
