[tool.poetry]
name = "ans-pycli"
version = "0.0.1"
description = "CLI for your python projects"
authors = ["alxnsmith <alx.n.smith@gmail.com>"]
readme = "README.md"
packages = [{include = "ans_pycli"}]

[tool.poetry.urls]
github="https://github.com/alxnsmith/ans-pycli"

[tool.poetry.scripts]
cli="ans_pycli.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"
pytest = "^7.2.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
