[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "qrcite"
version = "0.2.3"
authors = [
    { name = "Mathias", email = "mathias-handy@gmx.de" },
    { name = "Erik E. Lorenz", email = "erik@tuvero.de" }
]
description = "Small python tool to generate qr codes with doi links out of .bib files. "
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bibtexparser",
    "qrcode",
    "Pillow",
    "fonts",
    "font-fredoka-one",
]

[project.urls]
"Homepage" = "https://codeberg.org/Meph/qrcite/"

[project.scripts]
qrcite = "qrcite:__main__"
