[tool.poetry]
name = "tmktthreader"
version = "1.0.1"
description = ""
authors = ["ladettanguy <sti2dlab.ladettanguy@gmail.com>"]
license = "apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
