[tool.poetry]
name = "gces-dion-package"
version = "1.0.0"
description = "Pacote do trabalho de GCES."
authors = ["dionvitor <dionvictor11@gmail.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
